/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function runCommand(config: CellCommand) {
    return invoke()<RunId>("run_command", { config })
}

export function suggestPath(s: string, from: string) {
    return invoke()<PathSuggest>("suggest_path", { s,from })
}

export function userHomeDir() {
    return invoke()<string>("user_home_dir")
}

export type RunId = string
export type CellCommand = { kind: CellCommandKind; source: string }
export type CellCommandKind = { kind: "Shell"; working_directory: string } | { kind: "Lua" }
export type PathSuggest = { valid: boolean; closest_path: string }
