name: Cache dependencies
description: Install and cache dependencies, including any `node_modules` folders

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        cache-dependency-path: yarn.lock
        cache: yarn

    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable

    - name: Check Cache
      id: cache-check
      uses: actions/cache/restore@v3
      with:
        key: node-dep-cache-${{ runner.os }}-${{ hashFiles('yarn.lock', 'package.json') }}
        path: |
          **/node_modules
          .svelte-kit

    - name: Install dependencies
      if: steps.cache-check.outputs.cache-hit != 'true'
      shell: bash
      run: |
        yarn install --frozen-lockfile
        yarn prepare

    - name: Cache dependencies
      if: steps.cache-check.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        key: node-dep-cache-${{ runner.os }}-${{ hashFiles('yarn.lock', 'package.json') }}
        path: |
          **/node_modules
          .svelte-kit

    - name: Cache Rust dependencies
      id: rust-cache-check
      uses: Swatinem/rust-cache@v2
      with:
        cache-all-crates: true
        key: ${{ hashFiles('src-tauri/tauri.conf.json') }}

    - name: Install Rust dependencies
      if: steps.rust-cache-check.outputs.cache-hi != 'true'
      shell: bash
      run |
        cd src-tauri
        cargo fetch
      if: steps.
