name: Cache dependencies
description: Install and cache dependencies, including any `node_modules` folders

inputs:
  include-rust:
    description: Include Rust dependencies
    default: false

runs:
  using: "composite"
  steps:
    - name: install dependencies (ubuntu only)
      if: runner.os == 'Linux' && inputs.include-rust == 'true'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

    - uses: pnpm/action-setup@v2.4.0
      with:
        version: 8

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        cache-dependency-path: pnpm-lock.yaml
        cache: pnpm

    - name: Install Rust stable
      if: inputs.include-rust == 'true'
      uses: dtolnay/rust-toolchain@stable

    - name: Check Cache
      id: cache-check
      uses: actions/cache/restore@v3
      with:
        key: node-dep-cache-${{ runner.os }}-${{ hashFiles('yarn.lock', 'package.json') }}
        path: |
          **/node_modules
          .svelte-kit

    - name: Install dependencies
      if: steps.cache-check.outputs.cache-hit != 'true'
      shell: bash
      run: |
        # TODO: use pnpm ci when available
        pnpm install
        pnpm prepare

    - name: Cache dependencies
      if: steps.cache-check.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        key: node-dep-cache-${{ runner.os }}-${{ hashFiles('yarn.lock', 'package.json') }}
        path: |
          **/node_modules
          .svelte-kit

    - name: Cache Rust dependencies
      id: rust-cache-check
      if: inputs.include-rust == 'true'
      uses: Swatinem/rust-cache@v2
      with:
        cache-all-crates: true
        key: ${{ hashFiles('src-tauri/tauri.conf.json') }}

    - name: Install Rust dependencies
      if: steps.rust-cache-check.outputs.cache-hit != 'true' && inputs.include-rust == 'true'
      shell: bash
      run: |
        cd src-tauri
        cargo fetch
