name: Cache dependencies
description: Install and cache dependencies, including any `node_modules` folders

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        cache-dependency-path: yarn.lock
        cache: yarn

    - name: Check Cache
      id: cache-check
      uses: actions/cache/restore@v3
      with:
        key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
        path: "**/node_modules"

    - name: Install dependencies
      if: steps.cache-check.outputs.cache-hit != 'true'
      shell: bash
      run: |
        yarn install --frozen-lockfile

    - name: Cache dependencies
      if: steps.cache-check.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
        path: "**/node_modules"
