[package]
name = "tauri-plugin-webb-networking"
version = "0.1.0"
description = "Webb networking"

[build-dependencies]
tauri-plugin = { version = "2.0.0-beta.10", features = [ "build" ] }

[dependencies]
tauri = "2.0.0-beta.13"
