[package]
name = "server"
version = "0.1.0"
description = ""
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.60"

[dependencies]
rocket = { version = "0.5.1", features = ["secrets"] }
