name: Check
on: [push]

jobs:
  deps:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache-dependency-path: yarn.lock
          cache: yarn

      - name: Install dependencies
        run: |
          yarn install

          if ! test -z "`git diff --stat`"; then
            echo "Changes were found; please run 'yarn install' and commit the output."
            echo
            git diff --name-only
            exit 1
          fi

  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/dep-cache
      - name: Check Formatting
        run: |
          yarn format

          if ! test -z "`git diff --stat`"; then
            echo "Changes were found; please run 'yarn format' and commit the output."
            echo
            git diff --name-only
            exit 1
          fi

  types:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/dep-cache
      - name: Check Types
        run: yarn check
