name: Check
on: [push]

jobs:
  deps:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache-dependency-path: pnpm-lock.yaml
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install

          if ! test -z "`git diff --stat`"; then
            echo "Changes were found; please run 'pnpm install' and commit the output."
            echo
            git diff --name-only
            exit 1
          fi

  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/dep-cache
      - name: Check Formatting
        run: |
          pnpm format

          if ! test -z "`git diff --stat`"; then
            echo "Changes were found; please run 'pnpm format' and commit the output."
            echo
            git diff --name-only
            exit 1
          fi

  types:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/dep-cache
      - name: Check Types
        run: pnpm ts-check

  rs-types:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/dep-cache
      - name: Check Rust Types
        run: |
          cd src-tauri
          cargo check
