name: Check
on: [push]

jobs:
  deps:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache-dependency-path: yarn.lock
          cache: yarn

      - name: Install dependencies
        run: |
          yarn install

          if ! test -z "`git diff --stat`"; then
            echo "Changes were found; please run 'yarn install' and commit the output."
            echo
            git diff --name-only
            exit 1
          fi

  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/dep-cache
      - name: Check Formatting
        run: |
          yarn format

          if ! test -z "`git diff --stat`"; then
            echo "Changes were found; please run 'yarn format' and commit the output."
            echo
            git diff --name-only
            exit 1
          fi

  types:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/dep-cache
      - name: Check Types
        run: yarn check

  publish-app:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/dep-cache
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: 114434131
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
