name: Check
on: [push]

jobs:
  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/dep-cache
      - name: Check Formatting
        run: |
          pnpm format

          if ! test -z "`git diff --stat`"; then
            echo "Changes were found; please run 'pnpm format' and commit the output."
            echo
            git diff --name-only
            exit 1
          fi

  types:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/dep-cache
      - name: Check Types
        run: pnpm ts-check

  # rs-types:
  #   runs-on: ubuntu-22.04

  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         lfs: true
  #     - uses: ./.github/dep-cache
  #       with:
  #         include-rust: true
  #     - name: Check Rust Types
  #       run: |
  #         cd src-tauri
  #         cargo check
