name: Publish
on:
  push:
    branches: main

concurrency:
  group: publish-app
  cancel-in-progress: false

jobs:
  publish-app:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: ./.github/dep-cache

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: 114434131
