name: Publish
on:
  push:
    branches: main

concurrency:
  group: publish-app
  cancel-in-progress: false

jobs:
  publish-app:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ''
          - platform: 'windows-latest'
            args: ''


    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: ./.github/dep-cache
        with:
          include-rust: true

      - run: pnpm run build-libs

      - uses: tauri-apps/tauri-action@v0.5.14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: ./native
          tauriScript: pnpm tauri
          releaseId: 114434131
          args: ${{ matrix.args }}
